### ISSUE TITLE
Add Javascript linter

### ISSUE THREAD

**Issue by lacabra** [unicef/kindly-website#1]
Add and configure ESlint + Prettier + Husky.

If you want to propose a different setup, please discuss the details of your proposal on this issue before submitting a pull request.

Use lacabra/validate-digitalpublicgoods#14 for reference

**Comment by Ifeanyi30** [comment]
Yes! I'm here, I would love to take on this challenge

**Comment by lacabra** [comment]
Sorry @Ifeanyi30, I missed this comment from you. Yes, absolutely, you are most welcome to do so. Thanks! 🙏

**Comment by Ifeanyi30** [comment]
Thanks @lacabra

**Comment by Ashara-kosi** [comment]
Hello @Ifeanyi30, how is it going with this issue. I am still waiting for your pr to be merged so I can work on mine
Would you be needing help to speed up the process?

**Comment by Ifeanyi30** [comment]
Hi @Ashara-kosi, sorry for the delay. A little more configuration and review and it would be merged

**Comment by Ashara-kosi** [comment]
Not a problem at all @Ifeanyi30 
You could also add me as a collaborator on your repository if you would be needing help on rounding up
