### ISSUE TITLE
Add GitHub actions to enforce code style

### ISSUE THREAD

**Issue by lacabra** [unicef/kindly-website#2]
After having implemented #1, configure the CI through GitHub Actions to enforce the code style upon committing files to the repo.

**Comment by Ifeanyi30** [comment]
Hi @lacabra! Has this issue been assigned to anybody yet? Cause I would try to try

**Comment by Ifeanyi30** [comment]
Alright then, one it is.

**Comment by lacabra** [comment]
Issue #1 has been addressed and this PR is now ready to be worked on. Kindly confirm your interest to work on this or else I'd be happy to reassign. Thank you

**Comment by Ashara-kosi** [comment]
@lacabra I am still interested in working on this

**Comment by Ifeanyi30** [comment]
And I want to be a part of the experience too

**Comment by Ifeanyi30** [comment]
@Ashara-kosi  would you like to collaborate?

**Comment by Ashara-kosi** [comment]
Yeah sure.

**Comment by Ifeanyi30** [comment]
Hi @Ashara-kosi have you created a pull request for this yet?
