### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by lacabra** [unicef/kindly-website#9]
Setup Google Analytics for the Kindly's public website at https://kindly.unicef.io

**Comment by Ifeanyi30** [comment]
I would love to do this with you, if you don't mind.

**Comment by lacabra** [comment]
Thanks @Ifeanyi30 for your interest. That was a fairly trivial task, which was implemented int his commit 81d8f87e0d2095c2d96cdfa231f9b0f46e1cd7eb. If you are interested, you can learn more about the [react-ga4](https://www.npmjs.com/package/react-ga4) package, or a [guide like this one](https://medium.com/geekculture/how-to-use-google-analytics-on-reactjs-in-5-minutes-7f6b43017ba9)

**Comment by Ifeanyi30** [comment]
Thanks @lacabra
